-- Removed CASCADE from drops

DROP TABLE IF EXISTS available_interviewers;
DROP TABLE IF EXISTS interviews;
DROP TABLE IF EXISTS interviewers;
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS days;

CREATE TABLE days (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE appointments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  time VARCHAR(255) NOT NULL,
  day_id INTEGER REFERENCES days(id) ON DELETE CASCADE
);

CREATE TABLE interviewers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) NOT NULL
);

CREATE TABLE interviews (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student VARCHAR(255) NOT NULL,
  interviewer_id INTEGER REFERENCES interviewers(id) ON DELETE CASCADE,
  appointment_id INTEGER UNIQUE REFERENCES appointments(id) ON DELETE CASCADE
);

CREATE TABLE available_interviewers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  day_id INTEGER REFERENCES days(id) ON DELETE CASCADE,
  interviewer_id INTEGER REFERENCES interviewers(id) ON DELETE CASCADE
);
